# put your secret values and credentials here. do not share this file and do not push it to github
[sources]
user_name = "" # please set me up!
password = "" # please set me up!
security_token = "" # please set me up!

[sources.credentials]
project_id = "" # please set me up!
private_key = ""
client_email = "" # please set me up!
token_uri = ""

[destination.filesystem]
bucket_url = "" 
# bucket_url = ""
layout="{table_name}/{load_id}.{file_id}.{ext}"

[destination.credentials]
project_id = "" # please set me up!
private_key = ""
client_email = "" # please set me up!
token_uri = ""

[destination.bigquery]
location = "US"

[destination.bigquery.credentials]
project_id = "" # please set me up!
private_key = "" # please set me up!
client_email = "" # please set me up!
